-- database_firebird.lua

-- luacheck: no max line length

-- CHANGELOG
-- 1.2.1 - 2026-09-22 - DATEADD macros use DATEADD(UNIT, 0 +/- n, NOW) so named→? binds are not unary-negated
-- 1.2.0 - 2026-09-22 - JSON_INGEST_FUNCTION: Firebird 4 UDR call shape (no DEFAULT/SUSPEND); JRE drops DEFAULT NULL ON ERROR
-- 1.1.0 - 2026-09-19 - Added JSON_VALUE_FUNCTION UDR macro; fixed BROTLI_DECOMPRESS_FUNCTION to use ENGINE UDR with module!routine format
-- 1.0.0 - 2026-09-18 - Initial Firebird dialect (Lookup 030 key 6 relabel from Firebase)

-- NOTES
-- Firebird 4 native functions: BASE64_ENCODE/BASE64_DECODE, CRYPT_HASH(... USING SHA256).
-- Brotli decompression via UDR in extras/brotli_udf_firebird/.
-- JSON stored as BLOB SUB_TYPE TEXT; JSON_VALUE not native until Firebird 6 — use UDR/PSQL.
-- ${SCHEMA} is empty; database file (hydrogen_test.fdb) is the isolation boundary.

return {
    CHAR_2 = "CHAR(2)",
    CHAR_20 = "CHAR(20)",
    CHAR_50 = "CHAR(50)",
    CHAR_128 = "CHAR(128)",
    DATE = "DATE",
    DATETIME = "TIMESTAMP",
    FLOAT = "FLOAT",
    FLOAT_BIG = "DOUBLE PRECISION",
    INSERT_KEY_START = "-- ",
    INSERT_KEY_END = "",
    INSERT_KEY_RETURN = "RETURNING ",
    INTEGER = "INTEGER",
    INTEGER_BIG = "BIGINT",
    INTEGER_SMALL = "SMALLINT",
    JRS = "JSON_VALUE(",
    JRM = ", ",
    JRE = ")",
    NOW = "CURRENT_TIMESTAMP",
    PRIMARY = "PRIMARY KEY",
    REORG = "-- REORG TABLE",
    SERIAL = "INTEGER GENERATED BY DEFAULT AS IDENTITY",
    SESSION_SECS = "DATEDIFF(SECOND FROM CAST(:SESSION_START AS TIMESTAMP) TO CURRENT_TIMESTAMP)",
    SIZE_COLLECTION = "CHAR_LENGTH(collection)",
    SIZE_FLOAT = "4",
    SIZE_FLOAT_BIG = "8",
    SIZE_INTEGER = "4",
    SIZE_INTEGER_BIG = "8",
    SIZE_INTEGER_SMALL = "2",
    SIZE_TIMESTAMP = "8",
    TEXT = "VARCHAR(255)",
    TEXT_BIG = "BLOB SUB_TYPE TEXT",
    TIME = "TIME",
    TIMESTAMP = "TIMESTAMP",
    TIMESTAMP_TZ = "TIMESTAMP WITH TIME ZONE",
    TRMS = "DATEADD(MINUTE, 0 - ",
    TRME = ", ${NOW})",
    TRFS = "DATEADD(SECOND, 0 + ",
    TRFE = ", ${NOW})",
    TRFMS = "DATEADD(MINUTE, 0 + ",
    TRFME = ", ${NOW})",
    UNIQUE = "UNIQUE",
    VARCHAR_20 = "varchar(20)",
    VARCHAR_50 = "varchar(50)",
    VARCHAR_64 = "varchar(64)",
    VARCHAR_100 = "varchar(100)",
    VARCHAR_128 = "varchar(128)",
    VARCHAR_500 = "varchar(500)",

    -- Firebird requires FROM RDB$DATABASE for SELECT without tables
    DUMMY_TABLE = "FROM RDB$DATABASE",

    BASE64_START = "CAST(BASE64_DECODE(",
    BASE64_END = ") AS BLOB SUB_TYPE TEXT)",

    -- Password hash: BASE64_ENCODE(CRYPT_HASH(('0' || '<password>') USING SHA256))
    -- Returns base64-encoded SHA256 hash
    -- Usage: ${SHA256_HASH_START}'0'${SHA256_HASH_MID}'${HYDROGEN_DEMO_ADMIN_PASS}'${SHA256_HASH_END}
    SHA256_HASH_START = "BASE64_ENCODE(CRYPT_HASH((",
    SHA256_HASH_MID = " || ",
    SHA256_HASH_END = ") USING SHA256))",

    COMPRESS_START = "BROTLI_DECOMPRESS(BASE64_DECODE(",
    COMPRESS_END = "))",

    DROP_CHECK = "SELECT 'Refusing to drop table ${SCHEMA}${TABLE} – it contains data' WHERE EXISTS (SELECT 1 FROM ${SCHEMA}${TABLE})",

    -- Firebird 4 Brotli UDR
    -- Requires: libbrotli, brotli_udf_firebird UDR in Firebird UDR plugin directory
    -- Installation handled via extras/brotli_udf_firebird/
    -- The UDR shared library must be named brotli_decfn.so and placed in
    -- the Firebird UDR plugins directory (default: /plugins/udr).
    -- External name format: <module>!<routine> → brotli_decfn!brotli_decompress
    BROTLI_DECOMPRESS_FUNCTION = [[
        CREATE OR ALTER FUNCTION BROTLI_DECOMPRESS(compressed BLOB)
        RETURNS BLOB
        EXTERNAL NAME 'brotli_decfn!brotli_decompress'
        ENGINE UDR;
    ]],

    JSON = "BLOB SUB_TYPE TEXT",
    JIS = "json_ingest(",
    JIE = ")",
    JSON_INGEST_START = "json_ingest(",
    JSON_INGEST_END = ")",

    -- Firebird has no reserved-key semantics for JSON Schema documents.
    -- These macros alias json_ingest; no separate function object is required.
    JSON_INGEST_SCHEMA_START = "json_ingest(",
    JSON_INGEST_SCHEMA_END = ")",
    JSON_INGEST_SCHEMA_FUNCTION = "",

    -- Firebird 4 has no native JSON_VALUE (Firebird 6+). This UDR provides it.
    -- Requires: libjansson, json_udf_firebird UDR in Firebird UDR plugin directory
    -- Installation handled via extras/json_udf_firebird/
    -- Must be created BEFORE json_ingest (PSQL below calls JSON_VALUE for validation).
    -- External name format: <module>!<routine> → json_udfn!json_value
    JSON_VALUE_FUNCTION = [[
        CREATE OR ALTER FUNCTION JSON_VALUE(json_doc BLOB SUB_TYPE TEXT, json_path VARCHAR(255))
        RETURNS BLOB SUB_TYPE TEXT
        EXTERNAL NAME 'json_udfn!json_value'
        ENGINE UDR;
    ]],

    -- json_ingest PSQL function: validates and normalizes JSON, escaping
    -- control characters inside strings. Uses the JSON_VALUE UDR for validity
    -- checking on the fast path. Must be created after JSON_VALUE_FUNCTION.
    -- Firebird 4 UDR is 2-arg only (no DEFAULT NULL ON ERROR). Invalid JSON /
    -- missing path already return NULL from json_udfn. No SUSPEND in FUNCTIONs.
    JSON_INGEST_FUNCTION = [[
        CREATE OR ALTER FUNCTION json_ingest(s BLOB SUB_TYPE TEXT)
        RETURNS BLOB SUB_TYPE TEXT
        AS
        DECLARE i INTEGER;
        DECLARE L INTEGER;
        DECLARE ch CHAR(1);
        DECLARE out BLOB SUB_TYPE TEXT;
        DECLARE in_str SMALLINT;
        DECLARE esc SMALLINT;
        BEGIN
            out = '';
            in_str = 0;
            esc = 0;
            i = 1;
            L = CHAR_LENGTH(s);

            -- fast path: UDR returns NULL on invalid JSON
            IF (JSON_VALUE(s, '$') IS NOT NULL) THEN
            BEGIN
                RETURN s;
            END

            -- fallback: escape control chars in strings
            WHILE (i <= L) DO
            BEGIN
                ch = SUBSTRING(s FROM i FOR 1);
                IF (esc = 1) THEN
                BEGIN
                    out = out || ch;
                    esc = 0;
                END
                ELSE IF (ch = '\') THEN
                BEGIN
                    out = out || ch;
                    esc = 1;
                END
                ELSE IF (ch = '"') THEN
                BEGIN
                    out = out || ch;
                    in_str = 1 - in_str;
                END
                ELSE IF (in_str = 1 AND ch = ASCII_CHAR(10)) THEN
                BEGIN
                    out = out || '\n';
                END
                ELSE IF (in_str = 1 AND ch = ASCII_CHAR(13)) THEN
                BEGIN
                    out = out || '\r';
                END
                ELSE IF (in_str = 1 AND ch = ASCII_CHAR(9)) THEN
                BEGIN
                    out = out || '\t';
                END
                ELSE
                BEGIN
                    out = out || ch;
                END
                i = i + 1;
            END

            -- ensure result is JSON; NULL if still invalid
            IF (JSON_VALUE(out, '$') IS NULL) THEN
            BEGIN
                RETURN NULL;
            END

            RETURN out;
        END
    ]],

    -- DB2-style extras that Firebird does not need but must define to avoid ${UNSUBSTITUTED}
    BASE64ENCODE_START = "BASE64_ENCODE(",
    BASE64ENCODE_END = ")",

    BASE64ENCODEBINARY_START = "BASE64_ENCODE(",
    BASE64ENCODEBINARY_END = ")",

    -- Date/Time formatting for parameter testing
    DATETIME_FORMAT = "CAST(CURRENT_TIMESTAMP AS VARCHAR(30))",
    TIMESTAMP_FORMAT = "CAST(CURRENT_TIMESTAMP AS VARCHAR(30))",

    CONVERT_TZ_FUNCTION = "-- Firebird TIMESTAMP WITH TIME ZONE handles timezone natively",
}
