-- =============================================================================
-- SchemaTool remediation (NOT EXECUTED)
-- schematool 1.8.3 · phase 4 audit
-- design=acuranzo engine=sqlite schema=. database=/mnt/extra/Projects/Philement/elements/001-hydrogen/hydrogen/tests/artifacts/database/sqlite/hydrodemo.sqlite
-- migrations=/mnt/extra/Projects/Philement/elements/002-helium/acuranzo/migrations
-- normalize=loose
-- Generated: 20260825T021211Z
-- counts: {"total":365,"ok":364,"drift":0,"missing_load":1,"missing_apply":0,"anomalies":0,"orphans":0}
-- exit_code=2
-- Rule: Uncomment deliberately. Prefer Hydrogen LOAD/APPLY when possible.
-- Updating queries.code does NOT replay DDL against live tables.
-- Prefer a NEW forward migration when live schema must change.
-- Content match scope (v1): code + name + summary.
-- Orphan DB refs: captured to .mig for optional new-migration rebuild.
-- =============================================================================
--
-- ---------------------------------------------------------------------------
-- Ref 1364: missing LOAD and APPLY
-- Disk: acuranzo_1364.lua
-- Prefer: start Hydrogen with AutoMigration against this DB (LOAD then APPLY).
-- Do not hand-expand full DDL here (risk of double-apply on partial schemas).
-- ---------------------------------------------------------------------------
--
