-- Smoke test for json_udfn!json_value (run after sudo make install)
CREATE OR ALTER FUNCTION JSON_VALUE(
    json_doc BLOB SUB_TYPE TEXT,
    json_path VARCHAR(255)
)
RETURNS BLOB SUB_TYPE TEXT
EXTERNAL NAME 'json_udfn!json_value'
ENGINE UDR;
COMMIT;

SELECT CAST(JSON_VALUE(CAST('{"a":1,"b":"hi"}' AS BLOB SUB_TYPE TEXT), '$.b') AS VARCHAR(64)) AS b_val
FROM RDB$DATABASE;

SELECT CAST(JSON_VALUE(CAST('{"a":{"x":2}}' AS BLOB SUB_TYPE TEXT), '$.a.x') AS VARCHAR(64)) AS nested
FROM RDB$DATABASE;

SELECT CAST(JSON_VALUE(CAST('[10,20]' AS BLOB SUB_TYPE TEXT), '$[1]') AS VARCHAR(64)) AS arr1
FROM RDB$DATABASE;

SELECT CAST(JSON_VALUE(CAST('{"a":1}' AS BLOB SUB_TYPE TEXT), '$.missing') AS VARCHAR(64)) AS miss
FROM RDB$DATABASE;

SELECT CAST(JSON_VALUE(CAST('not-json' AS BLOB SUB_TYPE TEXT), '$') AS VARCHAR(64)) AS bad
FROM RDB$DATABASE;
