# CMake generated Testfile for 
# Source directory: /home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake
# Build directory: /home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_launch_plan "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/build/unity/src/launch/test_launch_plan")
set_tests_properties(test_launch_plan PROPERTIES  WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../build/unity/src/launch" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;922;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
add_test(test_payload "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/build/unity/src/payload/test_payload")
set_tests_properties(test_payload PROPERTIES  WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../build/unity/src/payload" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;922;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
add_test(test_swagger "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/build/unity/src/swagger/test_swagger")
set_tests_properties(test_swagger PROPERTIES  WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../build/unity/src/swagger" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;922;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
add_test(test_hydrogen "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/build/unity/src/test_hydrogen")
set_tests_properties(test_hydrogen PROPERTIES  WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../build/unity/src" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;922;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
add_test(hydrogen_basic_test "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../tests/22_startup_shutdown.sh")
set_tests_properties(hydrogen_basic_test PROPERTIES  ENVIRONMENT "CMAKE_BUILD=1" TIMEOUT "300" WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;950;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
add_test(hydrogen_compilation_test "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../tests/test_01_compilation.sh")
set_tests_properties(hydrogen_compilation_test PROPERTIES  ENVIRONMENT "CMAKE_BUILD=1" TIMEOUT "300" WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;955;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
add_test(hydrogen_dependencies_test "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../tests/test_16_library_dependencies.sh")
set_tests_properties(hydrogen_dependencies_test PROPERTIES  ENVIRONMENT "CMAKE_BUILD=1" TIMEOUT "300" WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;960;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
add_test(hydrogen_unity_tests "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/../tests/test_11_unity.sh")
set_tests_properties(hydrogen_unity_tests PROPERTIES  WORKING_DIRECTORY "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake" _BACKTRACE_TRIPLES "/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;965;add_test;/home/asimard/Projects/Philement/elements/001-hydrogen/hydrogen/cmake/CMakeLists.txt;0;")
