-- database_firebird.lua

-- luacheck: no max line length

-- CHANGELOG
-- 2.9.0 - 2026-07-04 - Added directional future-time macros TRFS/TRFE (seconds) and TRFMS/TRFME (minutes) for parity with SQLite fix (Test 41 SQLite JWT bug)
-- 2.8.1 - 2026-07-02 - Added REORG TABLE macro
-- 2.8.0 - 2026-07-02 - Added JSON_INGEST_SCHEMA (aliases json_ingest; JSON_VALUE accepts $ref/$id/$schema)
-- 2.7.0 - 2026-03-22 - Added VARCHAR_64
-- 2.6.0 - 2025-12-31 - Added fancy INSERT_ macros to get our new key value returned
-- 2.5.0 - 2025-12-31 - Added SIZE_ macros
-- 2.4.0 - 2025-12-30 - Added JRS, JRM, JRE macros for JSON value retrieval
-- 2.3.0 - 2025-12-29 - Added SESSION_SECS macro for session duration calculation
-- 2.2.0 - 2025-12-28 - Added TRMS and TRME macros for time calculations (Time Range Minutes Start/End)
-- 2.1.0 - 2025-11-23 - Added DROP_CHECK to test for non-empty tables prior to drop
-- 2.0.0 - 2025-11-16 - Added BASE64_START and BASE64_END macros

-- NOTES
-- Firebird 4 native functions: BASE64_ENCODE/BASE64_DECODE, CRYPT_HASH(... USING SHA256).
-- Brotli decompression via UDR in extras/brotli_udf_firebird/.
-- JSON stored as BLOB SUB_TYPE TEXT; JSON_VALUE not native until Firebird 6 — use UDR/PSQL.
-- ${SCHEMA} is empty; database file (testfb.fdb) is the isolation boundary.

return {
    CHAR_2 = "CHAR(2)",
    CHAR_20 = "CHAR(20)",
    CHAR_50 = "CHAR(50)",
    CHAR_128 = "CHAR(128)",
    DATE = "DATE",
    DATETIME = "TIMESTAMP",
    FLOAT = "FLOAT",
    FLOAT_BIG = "DOUBLE PRECISION",
    INSERT_KEY_START = "-- ",
    INSERT_KEY_END = "",
    INSERT_KEY_RETURN = "RETURNING ",
    INTEGER = "INTEGER",
    INTEGER_BIG = "BIGINT",
    INTEGER_SMALL = "SMALLINT",
    JRS = "JSON_VALUE(",
    JRM = ", ",
    JRE = " DEFAULT NULL ON ERROR)",
    NOW = "CURRENT_TIMESTAMP",
    PRIMARY = "PRIMARY KEY",
    REORG = "-- REORG TABLE",
    SERIAL = "INTEGER GENERATED BY DEFAULT AS IDENTITY",
    SESSION_SECS = "DATEDIFF(SECOND FROM CAST(:SESSION_START AS TIMESTAMP) TO CURRENT_TIMESTAMP)",
    SIZE_COLLECTION = "CHAR_LENGTH(collection)",
    SIZE_FLOAT = "4",
    SIZE_FLOAT_BIG = "8",
    SIZE_INTEGER = "4",
    SIZE_INTEGER_BIG = "8",
    SIZE_INTEGER_SMALL = "2",
    SIZE_TIMESTAMP = "8",
    TEXT = "VARCHAR(255)",
    TEXT_BIG = "BLOB SUB_TYPE TEXT",
    TIME = "TIME",
    TIMESTAMP = "TIMESTAMP",
    TIMESTAMP_TZ = "TIMESTAMP WITH TIME ZONE",
    TRMS = "DATEADD(-",
    TRME = " MINUTE TO ${NOW})",
    TRFS = "DATEADD(+",
    TRFE = " SECOND TO ${NOW})",
    TRFMS = "DATEADD(+",
    TRFME = " MINUTE TO ${NOW})",
    UNIQUE = "UNIQUE",
    VARCHAR_20 = "varchar(20)",
    VARCHAR_50 = "varchar(50)",
    VARCHAR_64 = "varchar(64)",
    VARCHAR_100 = "varchar(100)",
    VARCHAR_128 = "varchar(128)",
    VARCHAR_500 = "varchar(500)",

    -- Firebird requires FROM RDB$DATABASE for SELECT without tables
    DUMMY_TABLE = "FROM RDB$DATABASE",

    BASE64_START = "CAST(BASE64_DECODE(",
    BASE64_END = ") AS BLOB SUB_TYPE TEXT)",

    -- Password hash: BASE64_ENCODE(CRYPT_HASH(('0' || '<password>') USING SHA256))
    -- Returns base64-encoded SHA256 hash
    -- Usage: ${SHA256_HASH_START}'0'${SHA256_HASH_MID}'${HYDROGEN_DEMO_ADMIN_PASS}'${SHA256_HASH_END}
    SHA256_HASH_START = "BASE64_ENCODE(CRYPT_HASH((",
    SHA256_HASH_MID = " || ",
    SHA256_HASH_END = ") USING SHA256))",

    COMPRESS_START = "BROTLI_DECOMPRESS(BASE64_DECODE(",
    COMPRESS_END = "))",

    DROP_CHECK = "SELECT 'Refusing to drop table ${SCHEMA}${TABLE} – it contains data' WHERE EXISTS (SELECT 1 FROM ${SCHEMA}${TABLE})",

    -- Firebird 4 Brotli UDR
    -- Requires: libbrotli, brotli_udf_firebird plugin in Firebird UDR directory
    -- Installation handled via extras/brotli_udf_firebird/
    BROTLI_DECOMPRESS_FUNCTION = [[
        CREATE OR ALTER FUNCTION BROTLI_DECOMPRESS(compressed BLOB)
        RETURNS BLOB
        EXTERNAL NAME 'brotli_decfn'
        ENGINE BLR;
    ]],

    JSON = "BLOB SUB_TYPE TEXT",
    JIS = "json_ingest(",
    JIE = ")",
    JSON_INGEST_START = "json_ingest(",
    JSON_INGEST_END = ")",

    -- Firebird has no reserved-key semantics for JSON Schema documents.
    -- These macros alias json_ingest; no separate function object is required.
    JSON_INGEST_SCHEMA_START = "json_ingest(",
    JSON_INGEST_SCHEMA_END = ")",
    JSON_INGEST_SCHEMA_FUNCTION = "",

    JSON_INGEST_FUNCTION = [[
        CREATE OR ALTER FUNCTION json_ingest(s BLOB SUB_TYPE TEXT)
        RETURNS BLOB SUB_TYPE TEXT
        AS
        DECLARE i INTEGER;
        DECLARE L INTEGER;
        DECLARE ch CHAR(1);
        DECLARE out BLOB SUB_TYPE TEXT;
        DECLARE in_str SMALLINT;
        DECLARE esc SMALLINT;
        BEGIN
            out = '';
            in_str = 0;
            esc = 0;
            i = 1;
            L = CHAR_LENGTH(s);

            -- fast path: check validity without exception
            -- Firebird has no TRY/CATCH JSON parse; use JSON_VALUE to test
            IF (JSON_VALUE(s, '$' DEFAULT NULL ON ERROR) IS NOT NULL) THEN
            BEGIN
                SUSPEND;
                RETURN s;
            END

            -- fallback: escape control chars in strings
            WHILE (i <= L) DO
            BEGIN
                ch = SUBSTRING(s FROM i FOR 1);
                IF (esc = 1) THEN
                BEGIN
                    out = out || ch;
                    esc = 0;
                END
                ELSE IF (ch = '\') THEN
                BEGIN
                    out = out || ch;
                    esc = 1;
                END
                ELSE IF (ch = '"') THEN
                BEGIN
                    out = out || ch;
                    in_str = 1 - in_str;
                END
                ELSE IF (in_str = 1 AND ch = ASCII_CHAR(10)) THEN
                BEGIN
                    out = out || '\n';
                END
                ELSE IF (in_str = 1 AND ch = ASCII_CHAR(13)) THEN
                BEGIN
                    out = out || '\r';
                END
                ELSE IF (in_str = 1 AND ch = ASCII_CHAR(9)) THEN
                BEGIN
                    out = out || '\t';
                END
                ELSE
                BEGIN
                    out = out || ch;
                END
                i = i + 1;
            END

            -- ensure result is JSON
            IF (JSON_VALUE(out, '$' DEFAULT NULL ON ERROR) IS NULL) THEN
            BEGIN
                EXCEPTION CREATE EXCEPTION 32749 'Invalid JSON after normalization';
            END

            SUSPEND;
            RETURN out;
        END
    ]],

    -- Firebird native Base64 encoding (no UDF needed)
    BASE64ENCODE_START = "BASE64_ENCODE(",
    BASE64ENCODE_END = ")",

    BASE64ENCODEBINARY_START = "BASE64_ENCODE(",
    BASE64ENCODEBINARY_END = ")",

    -- Date/Time formatting for parameter testing
    DATETIME_FORMAT = "CAST(CURRENT_TIMESTAMP AS VARCHAR(30))",
    TIMESTAMP_FORMAT = "CAST(CURRENT_TIMESTAMP AS VARCHAR(30))",

    CONVERT_TZ_FUNCTION = "-- Firebird TIMESTAMP WITH TIME ZONE handles timezone natively",
}
