#!/usr/bin/env bash
# SchemaTool Firebird helpers — isql-fb runner and catalog type mapping.
#
# isql-fb reads ISC_USER and ISC_PASSWORD from the environment. The
# password is not a process argument. Callers scrub it from errors.
# A private FIREBIRD_LOCK directory is used because /tmp/firebird is
# often mode 770 and owned by the firebird group.
#
# Catalog lines (after trim) are:
#   T|<table>
#   C|<column>
#   M|<field_type>|<sub_type>|<char_len>|<precision>|<scale>|<null_flag>|<identity>
#   K|<column>|<pk_position>
# null_flag 1 means NOT NULL. identity 0 is ALWAYS, 1 is BY DEFAULT,
# -1 is not an identity column. Scale is Firebird's negative scale.
#
# CHANGELOG
# 1.0.0 - 2026-10-07 - Phase 1 shared isql runner and field-type map

# shellcheck disable=SC2034 # constants and maps read by callers

schematool_fb_scrub() {
    local text="$1"
    local pass="$2"
    local out="" tmp
    if [[ -z "${pass}" || -z "${text}" ]]; then
        printf '%s' "${text}"
        return 0
    fi
    tmp="${text}"
    while [[ "${tmp}" == *"${pass}"* ]]; do
        out+="${tmp%%"${pass}"*}***"
        tmp="${tmp#*"${pass}"}"
    done
    out+="${tmp}"
    printf '%s' "${out}"
}

# SQL text on stdin. isql stdout is written to dest. Read-only is the
# caller's SQL (SET TRANSACTION READ ONLY). This function does not
# execute DML of its own.
schematool_fb_isql() {
    local database="$1"
    local user="$2"
    local password_env="$3"
    local dest="$4"
    local pass="" err sqlfile lock rc safe
    if [[ ! -f "${database}" ]]; then
        echo "Error: firebird database file not found: ${database}" >&2
        return 1
    fi
    if ! command -v isql-fb >/dev/null 2>&1; then
        echo "Error: isql-fb not found" >&2
        return 1
    fi
    if [[ -n "${password_env}" ]]; then
        if [[ -z "${!password_env+x}" || -z "${!password_env}" ]]; then
            echo "Error: password env var '${password_env}' is not set" >&2
            return 1
        fi
        pass="${!password_env}"
    fi
    lock="$(mktemp -d "${TMPDIR:-/tmp}/schematool-fb-lock.XXXXXX")"
    err="$(mktemp "${TMPDIR:-/tmp}/schematool-fb-err.XXXXXX")"
    sqlfile="$(mktemp "${TMPDIR:-/tmp}/schematool-fb-sql.XXXXXX")"
    cat > "${sqlfile}"
    set +e
    FIREBIRD_LOCK="${lock}" FIREBIRD_TMP="${lock}" \
        ISC_USER="${user}" ISC_PASSWORD="${pass}" \
        isql-fb -q -b -pag 0 -ch UTF8 "${database}" -i "${sqlfile}" \
        >"${dest}" 2>"${err}"
    rc=$?
    set -e
    rm -rf "${lock}" "${sqlfile}"
    if [[ "${rc}" -ne 0 ]]; then
        # shellcheck disable=SC2311,SC2312 # read the isql error, then scrub the password before printing
        safe="$(schematool_fb_scrub "$(cat "${err}")" "${pass}")"
        echo "Error: isql-fb failed (db=${database})" >&2
        printf '%s\n' "${safe}" >&2
        rm -f "${err}"
        return 1
    fi
    rm -f "${err}"
    return 0
}

# Map one RDB$FIELDS row onto the migration SQL type, lowercased.
# Arguments: field_type sub_type char_len precision scale identity
schematool_fb_sql_type() {
    local ftype="$1"
    local fsub="$2"
    local clen="$3"
    local prec="$4"
    local scale="$5"
    local ident="$6"
    local base sc
    sc="${scale#-}"
    case "${ftype}" in
        7) base="smallint" ;;
        8) base="integer" ;;
        10) base="float" ;;
        12) base="date" ;;
        13) base="time" ;;
        14) base="char(${clen})" ;;
        16) base="bigint" ;;
        23) base="boolean" ;;
        27) base="double precision" ;;
        28) base="time with time zone" ;;
        29) base="timestamp with time zone" ;;
        35) base="timestamp" ;;
        37) base="varchar(${clen})" ;;
        261)
            if [[ "${fsub}" == "1" ]]; then
                base="blob sub_type text"
            elif [[ "${fsub}" == "0" ]]; then
                base="blob sub_type binary"
            else
                base="blob sub_type ${fsub}"
            fi
            ;;
        *) base="type(${ftype})" ;;
    esac
    if [[ "${ftype}" == "7" || "${ftype}" == "8" || "${ftype}" == "16" ]]; then
        if [[ "${fsub}" == "1" ]]; then
            base="numeric(${prec},${sc})"
        elif [[ "${fsub}" == "2" ]]; then
            base="decimal(${prec},${sc})"
        fi
    fi
    if [[ "${ident}" == "0" ]]; then
        base="${base} generated always as identity"
    elif [[ "${ident}" == "1" ]]; then
        base="${base} generated by default as identity"
    fi
    printf '%s\n' "${base}"
}

schematool_fb_trim() {
    local line="$1"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    printf '%s' "${line}"
}

# Read catalog lines on stdin. Optional argument is a comma list of
# tables that must appear even when the live file has no such table.
schematool_fb_catalog_json() {
    local requested="${1:-}"
    local line tname cname ftype fsub clen prec scale nflag ident pkpos
    local nullable dtype col_obj pk_json tables_json tbl raw
    local -a table_order=() req_arr=()
    local -A have_table=() col_lines=() pk_lines=()
    tname=""
    cname=""
    while IFS= read -r line || [[ -n "${line}" ]]; do
        # shellcheck disable=SC2311 # trim is a pure string edit
        line="$(schematool_fb_trim "${line}")"
        [[ -z "${line}" ]] && continue
        [[ "${line}" == \#* ]] && continue
        case "${line}" in
            T\|*)
                tname="${line#T|}"
                tname="${tname,,}"
                cname=""
                if [[ -z "${have_table[${tname}]+x}" ]]; then
                    have_table["${tname}"]=1
                    table_order+=("${tname}")
                    col_lines["${tname}"]=""
                    pk_lines["${tname}"]=""
                fi
                ;;
            C\|*)
                cname="${line#C|}"
                cname="${cname,,}"
                ;;
            M\|*)
                if [[ -z "${tname}" || -z "${cname}" ]]; then
                    echo "Error: catalog type row without a table and column" >&2
                    return 1
                fi
                IFS='|' read -r _ ftype fsub clen prec scale nflag ident <<< "${line}"
                # shellcheck disable=SC2310,SC2311 # type mapping is a pure string
                dtype="$(schematool_fb_sql_type "${ftype}" "${fsub}" "${clen}" "${prec}" "${scale}" "${ident}")"
                if [[ "${nflag}" == "1" ]]; then
                    nullable="false"
                else
                    nullable="true"
                fi
                col_lines["${tname}"]+="${cname}"$'\t'"${dtype}"$'\t'"${nullable}"$'\n'
                cname=""
                ;;
            K\|*)
                if [[ -z "${tname}" ]]; then
                    echo "Error: catalog primary-key row without a table" >&2
                    return 1
                fi
                IFS='|' read -r _ cname pkpos <<< "${line}"
                cname="${cname,,}"
                pk_lines["${tname}"]+="${pkpos}"$'\t'"${cname}"$'\n'
                cname=""
                ;;
            *)
                echo "Error: unrecognised catalog line" >&2
                return 1
                ;;
        esac
    done

    if [[ -n "${requested}" ]]; then
        table_order=()
        IFS=',' read -r -a req_arr <<< "${requested}"
        for raw in "${req_arr[@]+"${req_arr[@]}"}"; do
            # shellcheck disable=SC2311 # trim is a pure string edit
            tname="$(schematool_fb_trim "${raw}")"
            tname="${tname,,}"
            [[ -z "${tname}" ]] && continue
            if [[ -z "${have_table[${tname}]+x}" ]]; then
                have_table["${tname}"]=1
                col_lines["${tname}"]=""
                pk_lines["${tname}"]=""
            fi
            table_order+=("${tname}")
        done
    fi

    tables_json="[]"
    for tname in "${table_order[@]+"${table_order[@]}"}"; do
        local cols_json="[]"
        while IFS=$'\t' read -r cname dtype nullable; do
            [[ -z "${cname}" ]] && continue
            col_obj="$(jq -nc \
                --arg name "${cname}" \
                --arg dt "${dtype}" \
                --argjson nullable "${nullable}" \
                '{name:$name, data_type:$dt, nullable:$nullable, default:null}')"
            cols_json="$(jq -c --argjson c "${col_obj}" '. + [$c]' <<< "${cols_json}")"
        done <<< "${col_lines[${tname}]}"
        if [[ -n "${pk_lines[${tname}]}" ]]; then
            # shellcheck disable=SC2312 # order primary-key columns; jq still has to parse the names
            pk_json="$(printf '%s' "${pk_lines[${tname}]}" | sed '/^$/d' | sort -n | cut -f2- | jq -R . | jq -sc .)"
        else
            pk_json="[]"
        fi
        tbl="$(jq -nc \
            --arg table "${tname}" \
            --argjson columns "${cols_json}" \
            --argjson pk "${pk_json}" \
            '{table:$table, columns:$columns, primary_key:$pk, indexes:[]}')"
        tables_json="$(jq -c --argjson t "${tbl}" '. + [$t]' <<< "${tables_json}")"
    done
    jq -nc --arg schema "" --argjson tables "${tables_json}" \
        '{schema:$schema, tables:$tables}'
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "Error: source this file from a Firebird adapter" >&2
    exit 1
fi
