import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        HTMLElement: 'readonly',
        URL: 'readonly',
        Intl: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        indexedDB: 'readonly',
        WebSocket: 'readonly',
        requestAnimationFrame: 'readonly',
        getComputedStyle: 'readonly',
        MutationObserver: 'readonly',
        Node: 'readonly',
        crypto: 'readonly',
        TextEncoder: 'readonly',
        performance: 'readonly',
        AbortController: 'readonly',
        Buffer: 'readonly',
        global: 'readonly',
        process: 'readonly',
        require: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },
  {
    ignores: [
      'node_modules/',
      'dist/',
      'coverage/',
      'tests/lib/',
      'tests/*.sh',
      'src/init/',
    ],
  },
];
