#!/usr/bin/env bash
# Map a recorded Firebird isql catalog fixture with no live database.
#
# CHANGELOG
# 1.0.0 - 2026-10-07 - Phase 1 field-type fixture

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=extras/schematool/db/firebird_common.sh # type map under test
source "${HERE}/../db/firebird_common.sh"

FIXTURE="${HERE}/fixtures/firebird_catalog_isql.txt"
OUT="$(schematool_fb_catalog_json "accounts,missing_table,sample_types" < "${FIXTURE}")"

fail=0
expect() {
    local filter="$1"
    local want="$2"
    local got
    got="$(jq -r "${filter}" <<< "${OUT}")"
    if [[ "${got}" != "${want}" ]]; then
        echo "FAIL ${filter}" >&2
        echo "  want: ${want}" >&2
        echo "  got:  ${got}" >&2
        fail=1
    fi
}

expect '.schema' ''
expect '.tables[0].table' 'accounts'
expect '.tables[0].primary_key | join(",")' 'account_id'
expect '.tables[0].columns[] | select(.name=="account_id") | .data_type + " " + (.nullable|tostring)' 'integer false'
expect '.tables[0].columns[] | select(.name=="password_hash") | .data_type + " " + (.nullable|tostring)' 'char(128) true'
expect '.tables[0].columns[] | select(.name=="name") | .data_type + " " + (.nullable|tostring)' 'varchar(255) false'
expect '.tables[0].columns[] | select(.name=="summary") | .data_type + " " + (.nullable|tostring)' 'blob sub_type text false'
expect '.tables[0].columns[] | select(.name=="collection") | .data_type + " " + (.nullable|tostring)' 'blob sub_type text true'
expect '.tables[0].columns[] | select(.name=="created_at") | .data_type + " " + (.nullable|tostring)' 'timestamp with time zone false'
expect '.tables[1].table' 'missing_table'
expect '.tables[1].columns | length' '0'
expect '.tables[1].primary_key | length' '0'
expect '.tables[2].columns[] | select(.name=="small_one") | .data_type' 'smallint'
expect '.tables[2].columns[] | select(.name=="big_one") | .data_type' 'bigint'
expect '.tables[2].columns[] | select(.name=="num_one") | .data_type + " " + (.nullable|tostring)' 'numeric(10,2) false'
expect '.tables[2].columns[] | select(.name=="dec_one") | .data_type + " " + (.nullable|tostring)' 'decimal(8,2) true'
expect '.tables[2].columns[] | select(.name=="flag") | .data_type' 'boolean'
expect '.tables[2].columns[] | select(.name=="big_float") | .data_type' 'double precision'
expect '.tables[2].columns[] | select(.name=="small_float") | .data_type' 'float'
expect '.tables[2].columns[] | select(.name=="day") | .data_type' 'date'
expect '.tables[2].columns[] | select(.name=="clock") | .data_type' 'time'
expect '.tables[2].columns[] | select(.name=="stamp") | .data_type' 'timestamp'
expect '.tables[2].columns[] | select(.name=="stamp_tz") | .data_type' 'timestamp with time zone'
expect '.tables[2].columns[] | select(.name=="clock_tz") | .data_type' 'time with time zone'
expect '.tables[2].columns[] | select(.name=="blob_bin") | .data_type' 'blob sub_type binary'
expect '.tables[2].columns[] | select(.name=="ident_def") | .data_type' 'integer generated by default as identity'
expect '.tables[2].columns[] | select(.name=="ident_always") | .data_type' 'integer generated always as identity'
expect '.tables[2].columns[] | select(.name=="short_text") | .data_type' 'varchar(20)'
expect '.tables[2].primary_key | join(",")' 'big_one,small_one'

if [[ "${fail}" -ne 0 ]]; then
    exit 1
fi
echo "firebird catalog map fixture: ok"
exit 0
