-- Firebird SHA-256 Password Hash Fixture Test
--
-- This test verifies that Firebird's native CRYPT_HASH / BASE64_ENCODE
-- produces the same password hash bytes as the other engines (PostgreSQL,
-- MySQL, SQLite, DB2), ensuring Test 40 login works across all engines.
--
-- Fixture: account_id='0' + password='testpass'
-- Expected: CUQEdl7cgIo2iGBfQmsuosLbdT9uLVpbm/rRJGQlbw0=
--
-- The ${SHA256_HASH_START}${SHA256_HASH_MID}${SHA256_HASH_END} macros
-- expand to BASE64_ENCODE(CRYPT_HASH((<id> || <password>) USING SHA256))
--
-- Usage: isql-fb -user SYSDBA -password <pass> testfb.fdb < test_sha256_fixture.sql

SELECT '=== SHA-256 Password Hash Fixture ===' AS test FROM RDB$DATABASE;

-- The hash expression as generated by ${SHA256_HASH_*} macros:
--   account_id='0' || password='testpass'
--   BASE64_ENCODE(CRYPT_HASH(('0' || 'testpass') USING SHA256))
SELECT
    CAST(BASE64_ENCODE(CRYPT_HASH(('0' || 'testpass') USING SHA256)) AS VARCHAR(100))
    AS hash_result
FROM RDB$DATABASE;
-- Expected: CUQEdl7cgIo2iGBfQmsuosLbdT9uLVpbm/rRJGQlbw0=

-- Verify the hash matches across engines
SELECT CASE
    WHEN CAST(BASE64_ENCODE(CRYPT_HASH(('0' || 'testpass') USING SHA256)) AS VARCHAR(100))
         = 'CUQEdl7cgIo2iGBfQmsuosLbdT9uLVpbm/rRJGQlbw0='
    THEN 'PASS'
    ELSE 'FAIL'
END AS fixture_status
FROM RDB$DATABASE;

SELECT '=== Fixture complete ===' AS result FROM RDB$DATABASE;
